apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: t1-workspace
  namespace: kubeflow-user-example-com
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    notebooks.kubeflow.org/creator: user@example.com
    notebooks.kubeflow.org/server-type: jupyter
    container.apparmor.security.beta.kubernetes.io/t1: unconfined
  labels:
    app: t1
    environment: kubeflow-notebook
  name: t1
  namespace: kubeflow-user-example-com
spec:
  template:
    spec:
      containers:
      - env: []
        image: trandat81/notebook-triton:v2
        imagePullPolicy: IfNotPresent
        name: t1
        securityContext:
          seccompProfile:
            type: Unconfined
        resources:
          limits:
            cpu: "0.6"
            memory: 1.2Gi
          requests:
            cpu: "0.5"
            memory: 1Gi
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /home/jovyan
          name: t1-workspace
      serviceAccountName: default-editor
      tolerations: []
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
      - name: t1-workspace
        persistentVolumeClaim:
          claimName: t1-workspace