apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: t1-workspace
  namespace: kubeflow-user-example-com
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    notebooks.kubeflow.org/creator: user@example.com
    notebooks.kubeflow.org/server-type: jupyter
    container.apparmor.security.beta.kubernetes.io/t1: unconfined
  labels:
    app: t1
  name: t1
  namespace: kubeflow-user-example-com
spec:
  template:
    spec:
      containers:
      - env: []
        image: trandat81/jupyter-notebook:containerd-in-docker
        imagePullPolicy: IfNotPresent
        name: t1
        securityContext:
          seccompProfile:
            type: Unconfined
        resources:
          limits:
            cpu: "0.6"
            memory: 1.2Gi
          requests:
            cpu: "0.5"
            memory: 1Gi
        volumeMounts:
        - mountPath: /lib/modules
          name: lib-modules
        - mountPath: /run/containerd/containerd.sock
          name: containerd-socket 
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /home/jovyan
          name: t1-workspace
      serviceAccountName: default-editor
      tolerations: []
      volumes:
      - name: lib-modules
        hostPath: 
          path: /lib/modules
      - name: containerd-socket
        hostPath:
          path: /run/containerd/containerd.sock
          type: Socket
      - emptyDir:
          medium: Memory
        name: dshm
      - name: t1-workspace
        persistentVolumeClaim:
          claimName: t1-workspace
