apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: t1-workspace
  namespace: kubeflow-user-example-com
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi