apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kubeflow-user-example-com
  name: triton-access-role
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: kubeflow-user-example-com
  name: triton-access-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: triton-access-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: kubeflow-user-example-com
