apiVersion: v1
kind: Service
metadata:
  name: triton-notebook-service
  namespace: kubeflow-user-example-com
spec:
  selector:
    matchLabels:
      environment: kubeflow-notebook 
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
    - protocol: TCP
      port: 8000
      targetPort: 8000 
    - protocol: TCP
      port: 8001
      targetPort: 8001
    - protocol: TCP
      port: 8002
      targetPort: 8002 
  type: ClusterIP
