apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2024-12-03T08:29:04Z"
  generation: 1
  name: t1
  namespace: kubeflow-user-example-com
  ownerReferences:
  - apiVersion: kubeflow.org/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: Notebook
    name: t1
    uid: 6c6022e0-d48f-4418-acb7-6a1b498d8df6
  resourceVersion: "57944"
  uid: af69fcad-7ecf-4144-a13d-4473457a9b81
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      statefulset: t1
  serviceName: ""
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: t1
        notebook-name: t1
        statefulset: t1
    spec:
      containers:
      - env:
        - name: NB_PREFIX
          value: /notebook/kubeflow-user-example-com/t1
        image: trandat81/jupyter-notebook:v2
        imagePullPolicy: IfNotPresent
        name: t1
        ports:
        - containerPort: 8888
          name: notebook-port
          protocol: TCP
        resources:
          limits:
            cpu: 600m
            memory: "1Gi"
          requests:
            cpu: 500m
            memory: "1Gi"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket 
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /home/jovyan
          name: t1-workspace
        workingDir: /home/jovyan
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 100
      serviceAccount: default-editor
      serviceAccountName: default-editor
      terminationGracePeriodSeconds: 30
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - emptyDir:
          medium: Memory
        name: dshm
      - name: t1-workspace
        persistentVolumeClaim:
          claimName: t1-workspace
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  availableReplicas: 1
  collisionCount: 0
  currentReplicas: 1
  currentRevision: t1-6cc749d7b8
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: t1-6cc749d7b8
  updatedReplicas: 1
