apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    notebooks.kubeflow.org/creator: user@example.com
    notebooks.kubeflow.org/server-type: jupyter
  creationTimestamp: "2024-12-26T02:36:27Z"
  generation: 1
  labels:
    app: test
  name: test
  namespace: kubeflow-user-example-com
  resourceVersion: "462671"
  uid: 0341eb67-1c76-456b-ba7a-4bea2613dd81
spec:
  template:
    spec:
      containers:
      - env: []
        image: trandat81/jupyter-notebook:containerd-in-docker
        imagePullPolicy: IfNotPresent
        name: test
        resources:
          limits:
            cpu: "0.6"
            memory: 1.2Gi
          requests:
            cpu: "0.5"
            memory: 1Gi
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /run/containerd/containerd.sock
          name: containerd-socket-pvc
        - mountPath: /lib/modules/
          name: lib-modules-pvc
        - mountPath: /home/jovyan
          name: test-workspace
      serviceAccountName: default-editor
      tolerations: []
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
      - name: containerd-socket-pvc
        persistentVolumeClaim:
          claimName: containerd-socket-pvc
          readOnly: false
      - name: lib-modules-pvc
        persistentVolumeClaim:
          claimName: lib-modules-pvc
          readOnly: false
      - name: test-workspace
        persistentVolumeClaim:
          claimName: test-workspace
status:
  conditions:
  - lastProbeTime: "2024-12-26T02:36:59Z"
    lastTransitionTime: "2024-12-26T02:36:46Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: "2024-12-26T02:36:59Z"
    lastTransitionTime: "2024-12-26T02:36:51Z"
    status: "True"
    type: Initialized
  - lastProbeTime: "2024-12-26T02:36:59Z"
    lastTransitionTime: "2024-12-26T02:36:57Z"
    status: "True"
    type: Ready
  - lastProbeTime: "2024-12-26T02:36:59Z"
    lastTransitionTime: "2024-12-26T02:36:57Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: "2024-12-26T02:36:59Z"
    lastTransitionTime: "2024-12-26T02:36:42Z"
    status: "True"
    type: PodScheduled
  containerState:
    running:
      startedAt: "2024-12-26T02:36:53Z"
  readyReplicas: 1
