name: "wav2vec_py"
backend: "python"
max_batch_size: 16

input [
  {
    name: "waveform"
    data_type: TYPE_FP32
    dims: [-1]
    allow_ragged_batch: true
  }
]

output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [49, 768]
  }
]

instance_group [
  {
    kind: KIND_GPU
    gpus: [ 0]
  }
]

dynamic_batching {
  preferred_batch_size: [4, 8, 16]
  max_queue_delay_microseconds: 1000000
}
